version: 0.2 
env:
  variables:
    S3_BUCKET: ros-cicd-bucket
    APP_NAME: cicd
    CACHE_DIR: cache
    ROBOT_WS: robot_ws
    SIMULATION_WS: simulation_ws
    ROS_VERSION: melodic
    ROBOTAPP: robomaker-cicd-project-robot-app
    SIMAPP: robomaker-cicd-project-sim-app
    ACCOUNT: 498889106520
    REGION: us-east-1
    ECRURI: $ACCOUNT.dkr.ecr.$REGION.amazonaws.com
    ROBOTAPPARN: arn:aws:robomaker:us-east-1:498889106520:robot-application/robomaker-cicd-project-robot-app/1672664467753
    SIMAPPARN: arn:aws:robomaker:us-east-1:498889106520:simulation-application/robomaker-cicd-project-sim-app/1672664500263
    
phases: 
  install: 
    commands: 
       - apt-get update
       - apt-get install -y python3-pip python3-apt apt-transport-https ca-certificates wget
       - wget http://packages.osrfoundation.org/gazebo.key 
       - apt-key add gazebo.key
       - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list
       - apt-get update
       - pip3 install -U setuptools pip
       - pip3 install colcon-ros-bundle
       - pip3 install awscli
       - pip3 install boto3
       - sudo pip3 install vcstool
       - sudo apt-get install ros-$ROS_VERSION-octomap
       - sudo groupadd docker
       - sudo usermod -aG docker $USER
       - newgrp docker
  pre_build:
    commands:
      - . /opt/ros/$ROS_VERSION/setup.sh
      - rosdep update
      - sudo rosdep fix-permissions
      - rosws update --target-workspace ./$ROBOT_WS
      - rosdep install --from-paths ./$ROBOT_WS/src --ignore-src -r -y
      - vcs import robot_ws < ./$ROBOT_WS/.rosinstall
      - rosws update --target-workspace ./$SIMULATION_WS
      - rosdep install --from-paths ./$SIMULATION_WS/src --ignore-src -r -y
      - vcs import simulation_ws < ./$SIMULATION_WS/.rosinstall
  build: 
    commands: 
      - COLCON_LOG_PATH="$CACHE_DIR/$ROBOT_WS/logs" colcon build --base-paths "./$ROBOT_WS" --build-base "$CACHE_DIR/$ROBOT_WS/build" --install-base "$CACHE_DIR/$ROBOT_WS/install"
      - COLCON_LOG_PATH="$CACHE_DIR/$SIMULATION_WS/logs" colcon build --base-paths "./$SIMULATION_WS" --build-base "$CACHE_DIR/$SIMULATION_WS/build" --install-base "$CACHE_DIR/$SIMULATION_WS/install"
  post_build: 
    commands:
      - sudo docker system prune -a -f
      - sudo DOCKER_BUILDKIT=1 docker build . --build-arg ROS_DISTRO=$ROS_VERSION --build-arg LOCAL_WS_DIR=./$ROBOT_WS --build-arg APP_NAME=$ROBOTAPP -t $ROBOTAPP
      - sudo DOCKER_BUILDKIT=1 docker build . --build-arg GAZEBO_VERSION=gazebo-9 --build-arg ROS_DISTRO=$ROS_VERSION --build-arg LOCAL_WS_DIR=./$SIMULATION_WS --build-arg APP_NAME=$SIMAPP -t $SIMAPP
      - sudo aws ecr get-login-password --region $REGION |sudo docker login --username AWS --password-stdin $ECRURI
      - aws ecr delete-repository --repository-name $ROBOTAPP --force
      - aws ecr delete-repository --repository-name $SIMAPP --force
      - aws ecr create-repository --repository-name $ROBOTAPP
      - aws ecr create-repository --repository-name $SIMAPP
      - sudo docker tag $robotapp $ECRURI/$ROBOTAPP:latest
      - sudo docker tag $simapp $ECRURI/$ROBOTAPP:latest
      - sudo docker push $ECRURI/$ROBOTAPP
      - sudo docker push $ECRURI/$SIMAPP
      - aws robomaker update-robot-application --application $ROBOTAPPARN --robot-software-suite name=General --environment uri=$ECRURI/$ROBOTAPP:latest
      - aws robomaker update-simulation-application --application $SIMAPPARN --robot-software-suite name=General --simulation-software-suite name=SimulationRuntime --environment uri=$ECRURI/$SIMAPP:latest
cache:
  paths:
    - '$CACHE_DIR/**/*'
    - '$ROBOT_WS/src/deps/**/*'
    - '$SIMULATION_WS/src/deps/**/*'
